### PR TITLE
Create project with gradle template

### LINKED ISSUE #45: Create gradle projects with android-create-project
`android create project` excepts a `-g` flag to create a gradle project. The option to use this flag should be included in `android-create-project`.

### PR DESCRIPTION
**Pull request by vxcamiloxv**
Close  #45

### CODE REVIEW

**Comment by remvee** [comment]
Nice!  but..  I don't like the `read-from-minibuffer` bit because it makes a non interactive call to `android-create-project` impossible and it requires the user to figure out what their current gradle version is.  Can you make it a customizable variable?

**Comment by vxcamiloxv** [comment]
ok better, I will make the change

**Comment by vxcamiloxv** [comment]
the change was done

**Comment by remvee** [comment]
Great documentation, thanks.

**Pull request merged**
